version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: notifications
      POSTGRES_USER: karthikeyagvsr
      POSTGRES_PASSWORD: Venkat@1967g
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/notifications
      SPRING_DATASOURCE_USERNAME: karthikeyagvsr
      SPRING_DATASOURCE_PASSWORD: Venkat@1967g
      SPRING_MAIL_HOST: smtp.gmail.com
      SPRING_MAIL_PORT: 587
      SPRING_MAIL_USERNAME: psrinivasan1801@gmail.com
      SPRING_MAIL_PASSWORD: ygpt bvdc tezs uzfq
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: true
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: true

volumes:
  pgdata:
